apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-dev-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-dev
  template:
    metadata:
      labels:
        app: api-dev
    spec:
      containers:
      - name: api-dev-container
        image: asia.gcr.io/tough-racer-272817/api-dev:latest
        env:
        - name: _NODE_ENV
          value: dev
        ports:
        - containerPort: 3001
          name: http
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: api-dev-service
spec:
  selector:
    app: api-dev
  ports:
  - protocol: TCP
    targetPort: 3001
    port: 8000
    name: http
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-dev-horizontal-scaler
spec:
  maxReplicas: 30
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-dev-deployment
  targetCPUUtilizationPercentage: 90
