apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-dev-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-dev
  template:
    metadata:
      labels:
        app: api-dev
    spec:
      containers:
      - name: api-dev-container
        image: asia.gcr.io/tough-racer-272817/api-dev:latest
        env:
        - name: _NODE_ENV
          value: dev
        ports:
        - containerPort: 3001
          name: http
        resources:
          limits:
            cpu: 250m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: api-dev-service
spec:
  selector:
    app: api-dev
  ports:
  - protocol: TCP
    targetPort: 3001
    port: 443
    name: http
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-dev-horizontal-scaler
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-dev-deployment
  targetCPUUtilizationPercentage: 80
