steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/tough-racer-272817/api-$_NODE_ENV:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/tough-racer-272817/api-$_NODE_ENV:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'asia.gcr.io/tough-racer-272817/api-$_NODE_ENV:$SHORT_SHA', 'asia.gcr.io/tough-racer-272817/api-$_NODE_ENV:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/tough-racer-272817/api-$_NODE_ENV:latest']
# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#     - beta
#     - run
#     - deploy
#     - --region=asia-east1
#     - --image=asia.gcr.io/tough-racer-272817/api-$_NODE_ENV:latest
#     - --cpu=1
#     - --memory=128Mi
#     - --max-instances=1
#     - --platform=managed
#     - --port=3001
#     - --concurrency=1000
#     - --allow-unauthenticated
#     - api-$_NODE_ENV
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - apply
    - --filename=api-$_NODE_ENV.yaml
  env:
    - CLOUDSDK_COMPUTE_REGION=asia-east1-a
    - CLOUDSDK_COMPUTE_ZONE=asia-east1
    - CLOUDSDK_CONTAINER_CLUSTER=cluster-1
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - rollout
    - restart
    - deployment
    - api-$_NODE_ENV-deployment
  env:
    - CLOUDSDK_COMPUTE_REGION=asia-east1-a
    - CLOUDSDK_COMPUTE_ZONE=asia-east1
    - CLOUDSDK_CONTAINER_CLUSTER=cluster-1

images:
  - 'asia.gcr.io/tough-racer-272817/api-$_NODE_ENV:latest'
